### ISSUE TITLE
minor doc addition / problems with dynamodb local

### ISSUE THREAD

**Issue by dimaqq** [mhart/dynalite#100]
Hi @mhart , than you so much for dynalite!

It's made our tests ~2x faster (vs. dynamodb local) and ~10x less CPU intensive (now we can think of running tests in parallel).

During the conversion, it even uncovered a bug (luckily in our tests and not prod code), specifically, dynamodb has a default sort order for result set, dynalite follow it, dynamodb local does not.

The latter fact could be added to the "problems with dynamodb local" section of the readme :)

**Comment by mhart** [comment]
That's awesome to hear! There are still some recent features that dynalite hasn't caught up on, so I feel like it's hard to make the case like I used to be able to 😄
