### ISSUE TITLE
Add support for BillingMode

### ISSUE THREAD

**Issue by Gerst20051** [mhart/dynalite#106]
I'm getting the following errors when I try to use the OnDemand BillingMode.

```
MissingRequiredParameter: Missing required key 'ProvisionedThroughput' in params
UnexpectedParameter: Unexpected key 'BillingMode' found in params
```

**Comment by timqian** [comment]
Any update on this issue?

**Comment by mhart** [comment]
Yup, this has been pushed out with v3.1.0, thanks for reporting!

**Comment by Gerst20051** [comment]
@mhart thanks for the progress!
