### ISSUE TITLE
Leveldown@4 fails to build under Node 12, need to upgrade to leveldown@5

### ISSUE THREAD

**Issue by ronjouch** [mhart/dynalite#112]
Dynalite optDepends on `"leveldown": "^4.0.1"` (4.x), which fails to build under node 12.x. https://github.com/Level/leveldown/issues/628#issuecomment-489469869 says that:

> For node 12, you'll need `leveldown@5`.

See https://github.com/Level/leveldown/blob/master/UPGRADING.md

**Comment by mhart** [comment]
Have fixed this in version 3.0.0 – thanks for reporting!
