### ISSUE TITLE
UnexpectedParameter: Unexpected key 'TimeToLiveSpecification' found in params

### ISSUE THREAD

**Issue by jseppi** [mhart/dynalite#130]
When I try to use the [`TimeToLiveSpecification`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-timetolivespecification.html) Property, I get this error during creation:

```
/Users/jamesseppi/CODE/<project>/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

UnexpectedParameter: Unexpected key 'TimeToLiveSpecification' found in params
    at ParamValidator.fail (/Users/jamesseppi/CODE/<project>/node_modules/aws-sdk/lib/param_validator.js:50:37)
...
```

Does `TimeToLiveSpecification` need to be added to a validator?

**Comment by mhart** [comment]
That error looks like it's coming from the aws-sdk?

**Comment by bwitt** [comment]
I thought dynalite didn't support TTL https://github.com/mhart/dynalite/issues/103 ?

**Comment by mhart** [comment]
It doesn't – but the error the poster is referring to is coming from validation in the aws-sdk – it's got nothing to do with this library

**Comment by jseppi** [comment]
@mhart: Apologies; this is definitely an issue in aws-sdk. The `TimeToLiveSpecification` is not supported for some reason in `createTable` ([ref](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#createTable-property)). 
Thank you for your speedy responses, and for this module!
