### ISSUE TITLE
Re-push new image to quay.io or docker hub for schema version 2 of manifest

### ISSUE THREAD

**Issue by raviagarwal7** [mhart/dynalite#136]
We are trying to download images for dynalite from quay.io using https://github.com/NotGlop/docker-drag which does not support schema 1. The current dynalite images have been pushed with schema version 1 of the manifest. Quay.io supports manifest schema version 2 fully now - moby/buildkit#409 (comment)

Can we re-push to have schema 2 compatible images to either quay.io or docker-hub?

Also if you could share the original dockerfile, I can push with schema version 2 as well.

**Comment by mhart** [comment]
I don't know who's responsible for those docker images unfortunately – it's not from this repo
