### ISSUE TITLE
Support for `INDEXES` in ReturnConsumedCapacity

### ISSUE THREAD

**Issue by rclark** [mhart/dynalite#14]
It appears that [at least the scan operation](https://github.com/mhart/dynalite/blob/fba2eb51d24afba8d72c84c17ebc218609f9b8e3/actions/scan.js#L71-L72) doesn't support the `INDEXES` option you might specify for `ReturnConsumedCapacity`. Is this the case for other types of requests as well?

Thanks!

**Comment by mhart** [comment]
Sorry it took a while to get around to this! Should be all good now though. Released in v0.11.0
