### ISSUE TITLE
Add support for new JSON document datatypes (BOOL, M, L, NULL)

### ISSUE THREAD

**Issue by mhart** [mhart/dynalite#16]
https://aws.amazon.com/blogs/aws/dynamodb-update-json-and-more/
http://www.allthingsdistributed.com/2014/10/document-model-dynamodb.html

**Comment by JamesSkinner** [comment]
+1

**Comment by loshia** [comment]
+1

**Comment by mhart** [comment]
Done via https://github.com/mhart/dynalite/commit/b28545d2ebed888e47b2304d4d8908ba865034a5 and released in v0.10.0
