### ISSUE TITLE
0.5.1 Broken Dependency Upgrade - --path mode fails.

### ISSUE THREAD

**Issue by MalucoMarinero** [mhart/dynalite#20]
Heyo, just run into an issue with version 0.5.1. Downgrading to 0.5.0 works just fine.

LevelUPError: Installed version of LevelDOWN (1.0.0) does not match required version (~0.10.0)

The optional dependency of leveldown needs to be downgraded back to '0.10.*', setting it to '1.*' yields this error when running dynalite with the --path option. LevelUp is not yet updated to support leveldown@1.*

**Comment by mhart** [comment]
Oh, ouch – thanks for the heads up, looking into this now.

**Comment by mhart** [comment]
Thanks for that, fixed in v0.5.2 and I deprecated v0.5.1 on npm.
