### ISSUE TITLE
Add support for `ExpressionAttributeNames` and `ProjectionExpression` in `BatchGetItem`, `GetItem`, `Query` and `Scan`

### ISSUE THREAD

**Issue by mhart** [mhart/dynalite#23]

**Comment by turntayble81** [comment]
Hi Michael, it appears 'FilterExpression' isn't working on query, either..

**Comment by mhart** [comment]
@turntayble81 Good point! Have added to the title of https://github.com/mhart/dynalite/issues/24 as it's more closely related to `ConditionExpression` and the language parsing that needs to be done there

**Comment by turntayble81** [comment]
Thanks! Btw great project!

**Comment by mhart** [comment]
Just completed this in 76d0ba7aefd98eb30da4b2cd838fccf9e37c56f6 – published as v0.18.0
