### ISSUE TITLE
Add support for `ConditionExpression`, `KeyConditionExpression `, `ExpressionAttributeNames` and `ExpressionAttributeValues` in `DeleteItem`, `UpdateItem` and `PutItem` and `FilterExpression` in `Scan` and `Query`

### ISSUE THREAD

**Issue by mhart** [mhart/dynalite#24]
This library supports all the old methods of using conditions (`KeyConditions`, etc) – but should be updated at some point to support all the new grammar.

This is a significant undertaking as it will require writing a parser for all of the syntax supported here: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html

**Comment by SamVerschueren** [comment]
Hi. First of all, great project! I would really love using it for my tests. It seems KeyConditionExpression is not supported either.

**Comment by mhart** [comment]
@SamVerschueren good point! Updated the title. I actually haven't used *any* of the more recent query/scan functionality, so I haven't really had time to work on this :crying_cat_face:

**Comment by jaquadro** [comment]
+1 -- I'd also love to use this in my tests, but my projects are written with the new API.

**Comment by rebolyte** [comment]
:+1: Just ran into this issue as well.

**Comment by SamVerschueren** [comment]
I switched to using [DynamodbLocal](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html) in a Docker container. Works very well. This project is promising but it's hard to keep it maintained :+1:

**Comment by arvenil** [comment]
+1, because of that I've switched to [DynaoDBLocal](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html) too
Also error message is really weird currently
> A client error (ValidationException) occurred when calling the Query operation: Either the KeyConditions or KeyConditionExpression parameter must be specified in the request.

which suggest that dynalite is aware of "KeyConditionExpression" and that filling it should work, but id doesn't

**Comment by mhart** [comment]
@arvenil that error message just matches (exactly) what the error message is on production AWS DynamoDB instances – all error messages in dynalite aim to do the same.

**Comment by nchudleigh** [comment]
You should add a note about this in the readme.  Wasted a bunch of time getting this set up only to find this issue.

Great project, would love to be able to use it :)

**Comment by deitch** [comment]
This project is great, and much better for my testing environment than DynamoLocal from AWS. But the `KeyConditionExpression` and similar of the newer syntax are important. +1

**Comment by martindavid** [comment]
@mhart have you start developing on this?? I must go back to `dynamodb-local` to have that expression.

**Comment by stevecaldwell77** [comment]
+1

**Comment by mhart** [comment]
Just completed this in 76d0ba7aefd98eb30da4b2cd838fccf9e37c56f6 – published as v0.18.0

**Comment by fortiema** [comment]
﻿﻿Hi there, and thanks for open-sourcing this great tool!

Sorry to reopen this conversation, but after running a few tests today, it seems to me like the _KeyConditionExpression_ parameter is ignored when sending a Query to Dynalite (those queries work just fine with both AWS DynamoDB and DynamoDB Local). I get back the ubiquitous error message:

> botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Either the KeyConditions or KeyConditionExpression parameter must be specified in the request.

Using the legacy _KeyConditions_ of course works just fine, and combining both _KeyConditions_ and _KeyConditionExpression_ also returns results (instead of returning an error message like it should).

I peeked around the source a bit but I'm not familiar with JS.

Anyone else noticed this?
Cheers!

**Comment by mhart** [comment]
@fortiema hmmm, that sounds odd. So firstly, try using the latest version (v1.0.2) – and secondly are you sure you're using `KeyConditionExpression`?

Can you show me the code you're using to call it?

**Comment by vandanagaikwad** [comment]
hey hi, we are getting more than 100 items using scan() API with IN logical operator in FilterExpression, it works fine for less than 100 records. But as the records increases more than 100, it gives error like 
{
  "message": "Invalid FilterExpression: The IN operator is provided with too many operands; number of operands: 222",
  "code": "ValidationException",
  "time": "2016-05-24T14:03:14.844Z",
  "requestId": "QSMLVHIVIU41F2BAMFVLB2U1IVVV4KQNSO5AEMVJF66Q9ASUAAJG",
  "statusCode": 400,
  "retryable": false,
  "retryDelay": 0
}
So can you please let me know how can I increase the FilterExpression limit for getting more than 100 items in single query

**Comment by mhart** [comment]
@vandanagaikwad how are you getting this error? Can you show the code you're using (and which API)?

**Comment by vandanagaikwad** [comment]
Actually I am getting the array of matching u_ids dynamically from one table e.g.cnc_codes table and using those to get user details in dynamodb.scan() API with logical operator IN in FilterExpression from cnc_users table, bellow is my code

var filterExp = "#k_source =:source ";
        var expAttrNames = {
                '#k_source': 'k_source'
            };
        var expAttrValue = {
                ":source": {'S': k_source}
            };
  
       var params = {
            TableName: "cnc_codes",
            ProjectionExpression: "k_id_user",
            FilterExpression: filterExp,
            ExpressionAttributeNames: expAttrNames,
            ExpressionAttributeValues: expAttrValue
        };
        
        console.log("Scanning codes table.");
        dynamodb.scan(params, function(err, data){
           if(data)
{
var item= {
  "TableName": "cnc_users",
  "FilterExpression": "u_id IN(:v1,:v2,:v3,...:v299,:v300)",
  "ExpressionAttributeValues": {
    ":v1": {
      "N": "96"
    },
    ":v2": {
      "N": "63"
    },
    ":v3": {
      "N": "93"
    },
    .
	.
	.
    ":v299": {
      "N": "145"
    },
    ":v300": {
      "N": "86"
    }
 }
}
 dynamodb.scan(item, function(err, data1) {
                if (err) {
                    console.error("Unable to get table items. Error JSON:", JSON.stringify(err, null, 2));
                } else {
                    context.succeed(data1.Items);
                }                
});
}
});
I am not setting the limit for query because we are calling this API for exporting the user details by k_source field, which needs to return all the matching user details.
Please give me suitable solution for the same, I am using this code on AWS Lambda console.
Thanks in advance.

**Comment by vandanagaikwad** [comment]
Sorry I am mapping the data returned from cnc_codes table i.e. from 1st scan operation to second scan operation to get user details

**Comment by mhart** [comment]
@vandanagaikwad I'm a bit confused – are you using this project?

**Comment by vandanagaikwad** [comment]
Yes, I am using this project, Is their anything wrong? Please suggest

**Comment by mhart** [comment]
@vandanagaikwad how are you starting `dynalite`?

**Comment by vandanagaikwad** [comment]
Ohh you are talking about dynalite project, sorry I am not using this

**Comment by mhart** [comment]
@vandanagaikwad this is the `dynalite` project

**Comment by SamVerschueren** [comment]
@vandanagaikwad then why are you asking it here?

**Comment by vandanagaikwad** [comment]
Sorry for that, I just want to get suggestion from @mhart so I asked here

**Comment by mhart** [comment]
@vandanagaikwad for support on DynamoDB, best to ask over at the Amazon forums: https://forums.aws.amazon.com/forum.jspa?forumID=131

**Comment by vandanagaikwad** [comment]
Thanks :)

**Comment by SamVerschueren** [comment]
But if you are not using `dynalite`, you are basically asking for `DynamoDB` support. Either ask it on StackOverflow or on the Amazon support forums.

Sorry if this sounds rude (not intended), but people (not only you) should stop wasting time from project maintainers with support questions. GitHub issues are meant for **issues** regarding the **project**. If you need support, use the channels that are meant for that.

**Comment by mhart** [comment]
@SamVerschueren I think @vandanagaikwad just made a mistake and is probably a bit of a GitHub newbie

**Comment by SamVerschueren** [comment]
@mhart Sorry for the rude reply. It just happened to me quite often lately which is quite frustrating. But I understand, we all started as an OSS newbie :). No hard feelings.

**Comment by mhart** [comment]
No probs 👍  I definitely get frustrated on GH too sometimes – I find Twitter can be good therapy for that 😸

**Comment by vandanagaikwad** [comment]
Yes, sorry for that as I am new for GitHub, that's why I didn't know that only project related issues are posted here. It happened by mistakenly I am extremely sorry for wasting your time(I have not did it intentionally).

**Comment by SamVerschueren** [comment]
@vandanagaikwad No problem, it's ok :beers:

**Comment by fortiema** [comment]
@mhart Tried also on 1.0.2, in vain.

Sure, here's the example (using boto3 client API):
`results = dynamodb.query(
    TableName='test',
    KeyConditionExpression='id = :pid1',
    ExpressionAttributeValues={
        'pid1': {'S': '208eca87-75f0-485d-b7e9-66d384566869'}
    },
    ReturnConsumedCapacity='TOTAL'
)`

Without _ExpressionAttributeValues_, result is the same:
`results = dynamodb.query(
    TableName='test',
    KeyConditionExpression='id=208eca87-75f0-485d-b7e9-66d384566869',
    ReturnConsumedCapacity='TOTAL'
)`

**Comment by mhart** [comment]
@fortiema how very odd – does boto have like a "verbose" option where it will output the JSON it's sending to the server?

**Comment by mhart** [comment]
@fortiema actually, I think I've just reproduced with the AWS CLI, lemme check what the problem is

**Comment by mhart** [comment]
@fortiema nope, false alarm – I just wasn't using the CLI correctly 😄 

This works just fine for me (which uses Boto under the hood):

```console
aws dynamodb query --endpoint-url http://localhost:4567 \
  --table-name test \
  --key-condition-expression 'id=:pid' \
  --expression-attribute-values '{":pid": {"S": "208eca87-75f0-485d-b7e9-66d384566869"}}' \
  --return-consumed-capacity TOTAL
```

```
{
    "Count": 0,
    "Items": [],
    "ScannedCount": 0,
    "ConsumedCapacity": {
        "CapacityUnits": 0,
        "TableName": "test"
    }
}
```

The first example you've got there should actually fail with the error (`ExpressionAttributeValues contains invalid key: Syntax error; key: "pid"`) because you need to prefix it with a colon.

Your second example should fail with a syntax error in the KeyConditionExpression itself.

**Comment by mhart** [comment]
@fortiema Are you sure you're using boto correctly? The [syntax in the docs](http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.Python.04.html) looks a little different:

eg:
```python
response = dynamodb.Table('Movies').query(
    KeyConditionExpression=Key('id').eq('208eca87-75f0-485d-b7e9-66d384566869')
)
```

**Comment by fortiema** [comment]
@mhart Indeed there was a typo in my first example, but as you can guess it is not affecting the outcome: 

> botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Either the KeyConditions or KeyConditionExpression parameter must be specified in the request.

By the way, the last example you showed is from a different API (Table API, I am using the lower-level Client API), but to be exhaustive, yes I also tried using the Table API previously - Same results. 

Actually, I even tried using the Java SDK:

```java
DynamoDBQueryExpression<UserSetting> queryExpression = new DynamoDBQueryExpression<UserSetting>()
     	   	.withIndexName("test")
     	   	.withKeyConditionExpression("id = 208eca87-75f0-485d-b7e9-66d384566869")
    	   	.withExpressionAttributeValues(values);
```

>com.amazonaws.AmazonServiceException: Either the KeyConditions or KeyConditionExpression parameter must be specified in the request. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException;

Again, all these examples are working fine with DynamoDB Local and AWS DynamoDB. Quite intriguing that it seems to work using the CLI directly (haven't tried that myself) !

Let me poke around boto and my debugger, I'll try to send you the verbrose request.

**Comment by fortiema** [comment]
Here's the request object formed by boto3:

```python
{'headers': {'Content-Type': 'application/x-amz-json-1.0', 'X-Amz-Target': 'DynamoDB_20120810.Query', 'User-Agent': 'Boto3/1.3.1 Python/3.5.1 Darwin/15.3.0 Botocore/1.4.22'}, 'url_path': '/', 'url': 'http://127.0.0.1:8000/', 'query_string': '', 'body': b'{"TableName": "test", "ExpressionAttributeValues": {":pid1": {"S": "208eca87-75f0-485d-b7e9-66d384566869"}}, "ReturnConsumedCapacity": "TOTAL", "KeyConditionExpression": "id=:pid1"}', 'method': 'POST'}
```

Here's the debug log when sending that request:

>Making request for OperationModel(name=Query) (verify_ssl=True) with params: {'body': b'{"TableName": "test", "ExpressionAttributeValues": {":pid1": {"S": "208eca87-75f0-485d-b7e9-66d384566869"}}, "KeyConditionExpression": "id=:pid1", "ReturnConsumedCapacity": "TOTAL"}', 'url_path': '/', 'method': 'POST', 'headers': {'User-Agent': 'Boto3/1.3.1 Python/3.5.1 Darwin/15.3.0 Botocore/1.4.22', 'Content-Type': 'application/x-amz-json-1.0', 'X-Amz-Target': 'DynamoDB_20120810.Query'}, 'query_string': '', 'url': 'http://127.0.0.1:8000/'}

**Comment by mhart** [comment]
@fortiema are you really really sure you're using the latest version? It really doesn't make sense that that error can occur with any version > v1.0.0

Can you just double check that you've got it installed in the place that you're running it. Are you installing with `npm install -g dynalite`? Or are you installing and running `./node_modules/.bin/dynalite` locally?

**Comment by fortiema** [comment]
@mhart Seems that there was indeed confusion about which versions of Dynalite were deployed (we are using them in Dockers and I didn't double-check) - It was only running v1.0.0.

We've now tested extensively on 1.0.2 where the issue seems indeed to be resolved.

Sorry for the confusion created (makes me feel a bit stupid!), and thanks for your kind help!
