### ISSUE TITLE
Add support for `UpdateExpression` in `UpdateItem`

### ISSUE THREAD

**Issue by mhart** [mhart/dynalite#25]

**Comment by addisonj** [comment]
Any ETA on this? https://github.com/ryanfitz/vogels (a nodejs mapping/query library for dynamo) makes use of UpdateExpressions pretty heavily. 

I was very excited to be able to run this in the context of my node service, so if there is anyway I can help, let me know! 

Seems like a good first step might be a parser for update expressions into a something easier to apply to document?

**Comment by mhart** [comment]
Just completed this in 76d0ba7aefd98eb30da4b2cd838fccf9e37c56f6 – published as v0.18.0
