### ISSUE TITLE
Add support for `IndexName` to `Scan`

### ISSUE THREAD

**Issue by mhart** [mhart/dynalite#27]
http://aws.amazon.com/releasenotes/Amazon-DynamoDB/3930233905269910

**Comment by jasny** [comment]
> In DynamoDB, a Scan operation reads all of the items in a table, applies user-defined filtering criteria, and returns the selected data items to the application. This same capability is now available for secondary indexes too. To scan a local secondary index or a global secondary index, you specify the index name and the name of its parent table. By default, an index Scan returns all of the data in the index; you can use a filter expression to narrow the results that are returned to the application.
For more information, see the following:

> [Query and Scan Operations](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html) in the _Amazon DynamoDB Developer Guide_
[Scan](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html) in the _Amazon DynamoDB API Reference_

**Comment by mhart** [comment]
Added in v1.0.0
