### ISSUE TITLE
.close() doesn't seem to close levelup

### ISSUE THREAD

**Issue by mrjackdavis** [mhart/dynalite#30]
I'm experiencing some unexpected behaviour. I expect that when I call `.close()` on a dynalite server, the underlying Levelup database is closed. However, it seems that is not the case.

Here's an example:

    var dynalite = require('dynalite');

    var server = dynalite({path: './tmp/dynalite', createTableMs: 50});

    server.listen(4567,function(err){
      if(!err){
        // doThings();

        server.close(function(){
          // Expect server to be closed...
          var server2 = dynalite({path: './tmp/dynalite', createTableMs: 50});
          server2.listen(6789,function(err){
            // recieved an error "Uncaught OpenError: IO error: lock ./tmp/mockDynamo/LOCK: already held by process"
          });
        });
      }
    });

**Comment by mhart** [comment]
Thanks so much for reporting! Fixed in v0.11.2
