### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by tielur** [mhart/dynalite#31]
Are there any plans to have a GUI interface with this? I just recently installed this locally to try and use it for local development but it's been a pain to try to update the tables which I normally do through the GUI. I've taken a look at https://github.com/hij1nx/lev but that's pretty cumbersome as well, especially when trying to update JSON documents.

**Comment by mhart** [comment]
Nope, no plans at all, this is most definitely a server project.

Closest I can recommend usability-wise is the AWS CLI which should work fine with it – let me know if you have any issues!

http://docs.aws.amazon.com/cli/latest/reference/dynamodb/index.html#cli-aws-dynamodb

**Comment by tielur** [comment]
@mhart Thanks! For what it's worth the [AWS Toolkit for Eclipse](http://aws.amazon.com/eclipse/) works really well. They have a plugin for visual studio too. As much as I hate java and eclipse, it works well for the very little things I need to do directly to the table.
