### ISSUE TITLE
Missing `LastEvaluatedKey` in query response

### ISSUE THREAD

**Issue by rclark** [mhart/dynalite#34]
I believe I have a test case that proves the following scenario triggers some kind of dynalite bug:

- generate 1000 items to put which are large enough that the entire result cannot be returned in a single `query` response.
- use `dynamo.batchWriteItem` requests to put these items into dynalite in sets of 25
- scan the table, assert that there are 1000 records in the table
- query the table, response does not contain a `LastEvaluatedKey`

See https://gist.github.com/rclark/ff22c330f8d6791cb0bb for a script that plays out this scenario. The table schema and query details are from my application that picked up on a problem -- I'm not sure how much (if at all) those details play into the issue. I do know that running the same code against a live dynamodb table does not recreate the issue.

**Comment by mhart** [comment]
Confirmed! Thanks so much for the detailed test – I'll dig into what's happening now. There was definitely some weirdness with LastEvaluatedKey in the live instances that I tried to replicate, but I may have gone too far somewhere in there.

**Comment by mhart** [comment]
Bleh, for some reason I'm not checking the size of the query *at all* in Query – only in Scan. It's a pretty easy fix, I'll just spend some time adding some tests to ensure everything's ok.

**Comment by rclark** [comment]
Thanks a lot! I really appreciate how quick you get on these issues!

**Comment by mhart** [comment]
OK, have fixed this and published in v0.14.1 – sorry for the slight delay, was trying to get a bunch of weird edge case tests in there!
