### ISSUE TITLE
It takes to long to create a table

### ISSUE THREAD

**Issue by jasny** [mhart/dynalite#41]
When running dynalite with it's default settings, it should take half a second to create a table. However (on my system) it take a full 20 seconds to complete.

Running dynamlite **0.17.1**

#### How to reproduce

```sh
dynalite &
sleep 5

aws dynamodb create-table --table-name MusicCollection --attribute-definitions AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S --key-schema AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --endpoint-url=http://localhost:4567

STARTTIME=$(date +%s)
aws dynamodb wait table-exists --table-name MusicCollection --endpoint-url=http://localhost:4567
ENDTIME=$(date +%s)

echo "It took $(($ENDTIME - $STARTTIME)) seconds to create the table"
```

#### Output

```
....
It took 21 seconds to create the table
```

**Comment by mhart** [comment]
Hmmm, you sure you're talking to a local dynalite instance?

Also, how long does the CLI "wait" for in between checking?

If you can reproduce this in JS let me know.

**Comment by mhart** [comment]
I suspect this is an issue with the CLI "wait" command – or something like that.

If you do `aws dynamodb describe-table --table-name MusicCollection --endpoint-url=http://localhost:4567` you can see that it's in an `ACTIVE` state ~500ms after creation

**Comment by jasny** [comment]
Hi, yes I initially had this problem in PHP. I was able to reproduce it with the CLI, confirming it isn't a bug  with the AWS PHP SDK.

```php
use Aws\DynamoDb\DynamoDbClient;

$dynamodb = DynamoDbClient::factory([
    'region' => 'local',
    'endpoint' => 'http://localhost:4567',
    'credentials' => [
        'key'    => 'none',
        'secret' => 'none',
    ],
    'request.options' => [
        'connect_timeout' => 3
    ],
    'client.backoff' => false
]);

$dynamodb->createTable([
    'TableName' => self::TABLE_NAME,
    'AttributeDefinitions' => [
        [
            'AttributeName' => 'key',
            'AttributeType' => 'S'
        ]
    ],
    'KeySchema' => [
        [
            'AttributeName' => 'key',
            'KeyType'       => 'HASH'
        ]
    ],
    'ProvisionedThroughput' => [
        'ReadCapacityUnits'  => 1,
        'WriteCapacityUnits' => 1
    ]
]);

$dynamodb->waitUntil('TableExists', [
    'TableName' => self::TABLE_NAME
]);
```

**Comment by jasny** [comment]
If I do an `describeTable` call after 1 second, the status is 'ACTIVE' and the the `waitUntil` command returns right away.

However without the `describeTable` is consistently takes around 20 seconds.

```
#!/bin/bash
dynalite &
sleep 5

aws dynamodb create-table --table-name MusicCollection --attribute-definitions AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S --key-schema AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --endpoint-url=http://localhost:4567

sleep 1
aws dynamodb describe-table --table-name MusicCollection --endpoint-url=http://localhost:4567

STARTTIME=$(date +%s)
aws dynamodb wait table-exists --table-name MusicCollection --endpoint-url=http://localhost:4567
ENDTIME=$(date +%s)

echo "It took $(($ENDTIME - $STARTTIME)) seconds to create the table"

sleep 1
fuser -k -n tcp 4567
```

Results in

```
It took 0 seconds to create the table
```

---

```
#!/bin/bash
dynalite &
sleep 5

aws dynamodb create-table --table-name MusicCollection --attribute-definitions AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S --key-schema AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --endpoint-url=http://localhost:4567

STARTTIME=$(date +%s)
aws dynamodb wait table-exists --table-name MusicCollection --endpoint-url=http://localhost:4567
ENDTIME=$(date +%s)

echo "It took $(($ENDTIME - $STARTTIME)) seconds to create the table"

sleep 1
fuser -k -n tcp 4567
```

Results in 

```
It took 21 seconds to create the table
```

---

Maybe it's accidental quantum computing? The state is only defined when you look at it. :wink:

**Comment by mhart** [comment]
Hmmm, I have no real idea what could be causing that.

Any idea what the `wait` command is doing? It's not part of the DynamoDB API, so I always just assumed it was doing a DescribeTable/sleep/DescribeTable/sleep type situation.

**Comment by jasny** [comment]
## it's not a bug

The help of `wait table-exists` tells it all

> Wait until JMESPath query Table.TableStatus returns ACTIVE when polling
> with describe-table. It will poll every 20 seconds until  a  successful
> state  has been reached. This will exit with a return code of 255 after
> 25 failed checks.

When using an SDK 20 seconds is also the default. 

```php
    'waiters' => array(
        '__default__' => array(
            'interval' => 20,
            'max_attempts' => 25,
        ),
        '__TableState' => array(
            'operation' => 'DescribeTable',
        ),
        'TableExists' => array(
            'extends' => '__TableState',
            'success.type' => 'output',
            'success.path' => 'Table/TableStatus',
            'success.value' => 'ACTIVE',
            'ignore_errors' => array(
                'ResourceNotFoundException',
            ),
        ),
        'TableNotExists' => array(
            'extends' => '__TableState',
            'success.type' => 'error',
            'success.value' => 'ResourceNotFoundException',
        ),
    ),
```

**Comment by mhart** [comment]
Cool, nice tracking down! :+1:

**Comment by jasny** [comment]
For others facing the same issue, you can set the interval using the `waiter.interval` option. So in PHP, you'd do the following to poll each second:

```php
$dynamodb->waitUntil('TableExists', [
   'TableName' => 'MusicCollection',
   'waiter.interval' => 1
]);
```

**Comment by mseiwald** [comment]
Does anyone know how to do this in JS? Passing waiter.interval in params does not work:

    { [UnexpectedParameter: Unexpected key 'waiter.interval' found in params]
      message: 'Unexpected key \'waiter.interval\' found in params',
      code: 'UnexpectedParameter',
      time: Wed Jan 20 2016 12:20:07 GMT+0100 (CET) }

**Comment by mhart** [comment]
@mseiwald The SDK has `waitFor` for this purpose: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#waitFor-property

**Comment by mseiwald** [comment]
Sorry, if I was unclear. I already use `waitFor` but I don't know how to pass a custom poll interval.

**Comment by mhart** [comment]
Right, that's a question for the AWS SDK team – I see you've already asked it over there so I'm sure they can help you out on that: https://github.com/aws/aws-sdk-js/issues/881
