### ISSUE TITLE
Query with KeyConditionExpression not working.

### ISSUE THREAD

**Issue by RikNieuwoudt** [mhart/dynalite#42]
I was playing around with Dynalite over the holidays and found an issue with its handling of KeyConditionExpression and query. It appears that Dynalite doesn't do validations for KeyConditionExpression fully, or at all.

I couldn't find any threads on others having a similar issue, is it just me?

**Comment by mhart** [comment]
Yeah, this is covered by https://github.com/mhart/dynalite/issues/24
