### ISSUE TITLE
GSI pagination fails with overlapping range values

### ISSUE THREAD

**Issue by rclark** [mhart/dynalite#43]
Ran across this issue in a table like:

index | hash | range
--- | --- | ---
primary | collection | id
gsi | collection | created

If I load 100 items into the same collection, with unique ids but identical creation times, then a set of paginated queries against the GSI, with Limit set < 100, does not return all 100 records. I get one page with a LastEvaluatedKey, but the request for a second page returns no items.

https://gist.github.com/rclark/c652191b855f3bba3a30 is a demonstration of the issue that uses https://github.com/rclark/dynamodb-test. It's just a wrapper around dynalite that makes it easy to toggle between a "live" test and a dynalite test. This test passes on a live table but fails against dynalite.

**Comment by mhart** [comment]
Ooh, nice edge case with the identical values on a page boundary. Will look into this tonight hopefully

**Comment by mhart** [comment]
Thanks for the report @rclark ! Fixed and published as v0.17.3
