### ISSUE TITLE
NetworkingError: socket hang up

### ISSUE THREAD

**Issue by Hiteshm01** [mhart/dynalite#44]
I am getting this error
```javascript
{ [NetworkingError: socket hang up]
  message: 'socket hang up',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'localhost',
  retryable: true,
  time: Fri Jan 15 2016 15:27:57 GMT+0530 (IST) }``` 
while trying to create a table for testing.  Can someone please help me point to right direction?

**Comment by mhart** [comment]
@Hiteshm01 You might be causing `dynalite` to crash somehow. Can you show me the code you're using?

**Comment by Hiteshm01** [comment]
@mhart Code is pretty naive and I doubt it would break anything. Refer this gist https://gist.github.com/Hiteshm01/ecba65996fa14fc0ec76

**Comment by mhart** [comment]
Is that trying to connect using HTTPS?

**Comment by Hiteshm01** [comment]
No, but when I am running dynalite, it is taking IPv6 convention, which might be actual reason for failure
```error
Listening at http://:::4567
```
On trying similar stuff on another box, it was listning on 0.0.0.0
```error
Listening at http://0.0.0.0:4567
```
socket hang up error was common in both cases.

**Comment by mhart** [comment]
@Hiteshm01 this works fine for me: https://gist.github.com/mhart/9141848bcc34ba9d9d8a

I think it might be something to do with all the http config stuff you're doing.

**Comment by mhart** [comment]
And `Listening at http://:::4567` is fine – that shouldn't be a problem

**Comment by mhart** [comment]
I also notice you're not using `http://` in the endpoint – again, I think the SDK might be trying to connect using HTTPS/SSL

**Comment by Hiteshm01** [comment]
I removed ```http:// ``` because it was throwing below error 
```error 
NetworkingError: Protocol "http:" not supported. Expected "https:
```
while https ends in same socket hung up error.

@mhart Do you think aws-sdk version might be a difference? I am using 2.2.30.

**Comment by mhart** [comment]
@Hiteshm01 no I don't think it's different – I honestly think it's all the weird http config stuff you're doing – you've got the agent set to be `httpsAgent` for example.

Perhaps just start with the default http settings, and then slowly add your own customisations until it fails, then you can figure out which config is causing it to error.

**Comment by Hiteshm01** [comment]
It was indeed that http config stuff which was causing issue. Starting from a clean slate worked. 

Thanks for guidance. Much appriciated.

**Comment by mhart** [comment]
No probs, glad you got it working! :+1:
