### ISSUE TITLE
Add size calculations for new attribute types (M, L, NULL, BOOL)

### ISSUE THREAD

**Issue by chook** [mhart/dynalite#47]
The DynamoDB API now supports more attributes such as Map, List, Null and Boolean.

**Comment by mhart** [comment]
I added some support for this a while back, but not sure how far I got:

https://github.com/mhart/dynalite/blob/9f0dec303c8519c7edec184eabe42046c64847cb/validations/index.js#L45-L74

What issues are you seeing in particular?

**Comment by chook** [comment]
I was reading the code and noticed lack of support here: https://github.com/mhart/dynalite/blob/master/db/index.js#L342

Since you haven't added anything to the README I figured the new attributes are NOT completely supported.

**Comment by mhart** [comment]
@chook OK, have adjusted the issue title accordingly

**Comment by mhart** [comment]
Fixed as of v0.18.3

**Comment by chook** [comment]
👍
