### ISSUE TITLE
Dynalite is using a lot of RAM in LevelDB store (--path)

### ISSUE THREAD

**Issue by chook** [mhart/dynalite#48]
After 5 days of not really extensive usage the RAM of the node process reached 12GB/16GB.

Perhaps you know if it's a known dynalite/leveldb/node issue?

**Comment by mhart** [comment]
@chook were you using the default in-memory memdown option? If so, then yeah, that's expected (assuming you were adding a lot of data?)

If you add the `path` option then `dynalite` will create an on-disk LevelDB database that should alleviate this.

**Comment by mhart** [comment]
Ugh – sorry – didn't read the title, obviously

**Comment by mhart** [comment]
I guess I can't really comment without knowing the details of how much data you've added – is it possible to create a reproducible test case that indicates dynalite might be leaking memory (instead of it just being leveldb using as large a resident size as it can)?

**Comment by chook** [comment]
I will try to come up with a test. Thanks for checking in a replying! The project is waking up :dancer:

**Comment by mhart** [comment]
@chook any news on this?

**Comment by mhart** [comment]
@chook any news on this?

**Comment by chook** [comment]
sadly this hasn't reproduced, I'll reopen if i have a test case.. thanks!
