### ISSUE TITLE
Problem with query while ScanIndexForward is false

### ISSUE THREAD

**Issue by chook** [mhart/dynalite#50]
Querying a hash backwards results in 
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:471) ~[aws-java-sdk-core-1.9.14.jar:na]

I tracked the code to this line:
https://github.com/mhart/dynalite/blob/master/actions/query.js#L108

Does that mean at a certain point a table is too big to support query with backward scanning?

**Comment by mhart** [comment]
I have no idea – how big is the table in question? Can you just adjust the timeout on the SDK side?

**Comment by mhart** [comment]
@chook any word on this?

**Comment by chook** [comment]
Hi @mhart - you specifically say that reverse scanning is not optimized so we just stopped using it :) any thoughts when you might come back and implement it?

**Comment by mhart** [comment]
It's not something particularly high on the TODO list – it should function correctly which is the main priority for a mock DB – if you can find a specific set of params that break it, then file another issue.

If it was a performance issue, then I'm guessing the table in question must have been really large? Basically it just falls back to a full table scan in these cases – so it shouldn't be any slower than a normal Scan – it's just not going to be as fast as a Query.

Going to close this, but if you can find a reproducible test case I'll look into it. Thanks!

**Comment by chook** [comment]
thanks for commenting @mhart - is it possible to have a quick chat with you privately? you can find me at chook (dot) harel at gmail - highly appreciated.

**Comment by mhart** [comment]
Queries now use proper LevelDB ranges as of v1.0.0
