### ISSUE TITLE
Configurable max record size

### ISSUE THREAD

**Issue by rclark** [mhart/dynalite#53]
While DynamoDB's documented limit is 400kb, it is possible to request an increase. Could dynalite allow for a configurable max record size to accommodate testing systems where this limit has been increased?

**Comment by rclark** [comment]
For now I'm circumventing the issue via

```js
require('dynalite/db/index').MAX_SIZE = 1024 * 1024;
```

... which feels a little icky.

**Comment by mhart** [comment]
Yeah, I mean... that's pretty close to what I'd do anyway. Do you want it to be available via the CLI, or just programmatically?

**Comment by rclark** [comment]
I imagined programmatically, similar to `deleteTableMs` configuration options. It was clear though, that such an adjustment would really wreck havoc on how modules depend on each other internally.

This approach works for now, but it feels like reaching behind the curtains -- I can't honestly depend on the file-system structure as part of the API.

**Comment by mhart** [comment]
Yeah, np – I'll take a look at it once I'm done with all the Expression stuff, which is a monster.

**Comment by rclark** [comment]
> once I'm done with all the Expression stuff, which is a monster.

Yeah it is, and support will also be incredibly useful. Thanks in advance.

**Comment by mhart** [comment]
Added this in v0.19.0 – let me know if there are any other configurable limits that you can request an increase on that would be worth including like this

**Comment by mhart** [comment]
(added as `maxItemSizeKb` btw)
