### ISSUE TITLE
Unable to create GSI indices in 0.18.0

### ISSUE THREAD

**Issue by tmbull** [mhart/dynalite#54]
In `0.17.4` I was able to create a global secondary index with the following configuration:

Name: "ResourceId-SourceId-index" 
Partition Key: "ResourceId" 
Sort Key: "SourceId"
Projected Attributes: All 
Read/Write capacity: 20/20

in `0.18.0` this operation fails with a `400` error and the following error message:

```
"One or more parameter values were invalid: Select type ALL_ATTRIBUTES is not supported for global secondary index undefined because its projection type is not ALL"
```

We are using the Haskell `aws` library, but I do not think that is part of the issue, as the operation worked fine in the prior version and also on Dynamo itself. Log output including the request body is as follows: 

```
Debug: Host: "127.0.0.1"
Debug: Path: "/"
Debug: Query string: ""
Debug: Body: "{\"KeyConditions\":{\"EntityId\":{\"AttributeValueList\":[{\"S\":\"00000000-0000-0000-0000-000000000000\"}],\"ComparisonOperator\":\"EQ\"}},\"ConsistentRead\":false,\"ReturnConsumedCapacity\":\"NONE\",\"ScanIndexForward\":true,\"Select\":\"ALL_ATTRIBUTES\",\"TableName\":\"test-resolver\"}"
Debug: Response status: Status {statusCode = 400, statusMessage = "Bad Request"}
Debug: Response header 'x-amzn-RequestId': 'RURN4KIOMEXTZ5TPZITM1ZKMEIUBBWCPDDMFSP31RISGRMA9PYOS'
Debug: Response header 'x-amz-crc32': '81088140'
Debug: Response header 'Content-Type': 'application/x-amz-json-1.0'
Debug: Response header 'Content-Length': '233'
Debug: Response header 'Date': 'Thu, 14 Apr 2016 19:47:04 GMT'
Debug: Response header 'Connection': 'keep-alive'
```

Please let me know if I can provide any further assistance. Thanks!

**Comment by dmjio** [comment]
+1

**Comment by mhart** [comment]
Ouch, ok, looking into this – sorry for the breakage

**Comment by mhart** [comment]
Should be fixed in 0.18.1 – please let me know if you have any issues!

(seems like this was missed because the haskell aws client specifies a bunch of attributes that are already defaults, and there weren't enough tests testing what should happen when these defaults are actually supplied!)

**Comment by tmbull** [comment]
@mhart I tested this today, and my issue is indeed fixed. Thanks for getting to it so quickly!

**Comment by dmjio** [comment]
Thanks @mhart!

On Fri, Apr 15, 2016 at 2:45 PM, Tristan Bull <notifications@github.com>
wrote:

> @mhart <https://github.com/mhart> I tested this today, and my issue is
> indeed fixed. Thanks for getting to it so quickly!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mhart/dynalite/issues/54#issuecomment-210613744>
>



-- 
Cell: 1.630.740.8204
