### ISSUE TITLE
Validate between and raise error

### ISSUE THREAD

**Issue by sshquack** [mhart/dynalite#55]
Hello @mhart,

Thank you for creating Dynalite!

While testing against DynamoDB and Dynalite, I noticed an inconsistency in validating the `BETWEEN` key condition expression values.

Steps to validate the issue:

Sample Table schema:
```
      TableName: 'sometable',
      KeySchema: [
        {AttributeName: 'hashKey', KeyType: 'HASH'},
        {AttributeName: 'rangeKey', KeyType: 'RANGE'}
      ],
      AttributeDefinitions: [
        {AttributeName: 'hashKey', AttributeType: 'S'},
        {AttributeName: 'rangeKey', AttributeType: 'N'}
      ]
```

Add two items with ranges 0 and 1 under the same hashKey "hello":
```
      TableName: 'sometable',
      Item: {
        hashKey: {S: 'hello'},
        rangeKey: {N: 0}
      },
...
      Item: {
        hashKey: {S: 'hello'},
        rangeKey: {N: 1}
      },
```

Query the table using `BETWEEN` range `0 and 1`:
```
      TableName: 'sometable,
      KeyConditionExpression: 'hashKey = "hello" AND rangeKey BETWEEN 0 AND 1'
```

 | Status | Output
----|---|---
DynamoDB | Ok | [item with rangeKey 0, item with rangeKey 1]
Dynalite | Ok | [item with rangeKey 0, item with rangeKey 1]

Query the table using `BETWEEN` range `2 and 1`:
```
      TableName: 'sometable,
      KeyConditionExpression: 'hashKey = "hello" AND rangeKey BETWEEN 2 AND 1'
```

 | Status | Output
----|---|---
DynamoDB | Error | ValidationException: Invalid KeyConditionExpression: The BETWEEN operator requires upper bound to be greater than or equal to lower bound; lower bound operand: AttributeValue: {N:2}, upper bound operand: AttributeValue: {N:1}
Dynalite | Ok | **no error thrown**

The fix for this issue is straightforward.
```javascript
      if (comparisonOperator === 'BETWEEN') {
        var lowerBound = data.KeyConditions[attr].AttributeValueList[0];
        var upperBound = data.KeyConditions[attr].AttributeValueList[1];

        // at this point AttributeValueList for the BETWEEN op looks like: [ {N: '42'}, {N: '4.2'} ]
        if (Object.keys(lowerBound).join('') === 'N' && Object.keys(upperBound).join('') === 'N') {
          var lowerBoundValue = Number(lowerBound.N);
          var upperBoundValue = Number(upperBound.N);

          if (lowerBoundValue > upperBoundValue) {
            var errMsg = 'Invalid KeyConditionExpression: The BETWEEN operator requires upper bound to be greater ' +
              'than or equal to lower bound; lower bound operand: AttributeValue: ' + JSON.stringify(lowerBound) +
              ', upper bound operand: AttributeValue: ' + JSON.stringify(upperBound);
            return cb(db.validationError(errMsg));
          }

        }

      }
```

Adding the above check after this line https://github.com/mhart/dynalite/blob/master/actions/query.js#L61 fixes this issue. Could you please validate this check patch, and possibly add this to dynalite? I'm happy to send a PR as well.

Thanks!

**Comment by mhart** [comment]
Thanks for looking into this @sshquack – you're right that I wasn't checking those boundary conditions – this is now fixed and published as v0.19.1
