### ISSUE TITLE
describeTable does not return an ACTIVE status

### ISSUE THREAD

**Issue by lukiano** [mhart/dynalite#58]
I'm using dynalite, and when I create a table and then call describeTable, I'm always getting a CREATING status, even after 40 seconds (max I tried) after the createTable was issued.

**Comment by mhart** [comment]
@lukiano can you give me some more details on how you're using dynalite, and the client code you're using to check this?

[There are tests](https://github.com/mhart/dynalite/blob/master/test/createTable.js#L1155-L1174) to ensure CreateTable results in an ACTIVE status and they're currently passing, so I suspect it's something to do with your setup or your DynamoDB client.

**Comment by lukiano** [comment]
Hmm, I just tried the test in a different machine and it passed. Let me do some more tests and if my computer is faulty in some way, then I'll close this. Thanks for the prompt response

**Comment by lukiano** [comment]
What happens is that the AWS SDK for Node.JS caches the result of describeTable. The first time going to dynalite it returned a CREATING status, but then dynalite changed to ACTIVE, but the describeTable method was still returning CREATING.

**Comment by mhart** [comment]
@lukiano woah, really? Is that documented somewhere? It doesn't seem to be mentioned in the normal docs: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#describeTable-property

**Comment by lukiano** [comment]
We attached a proxy sniffer and no requests were being sent to dynalite after the first one

**Comment by mhart** [comment]
@lukiano I suspect there's something up with your code. The following works just fine for me (using the AWS SDK):
```js
var AWS = require('aws-sdk')

var db = new AWS.DynamoDB({endpoint: 'http://localhost:4567'})

function checkTable(err, data) {
  if (err) throw err
  var status = (data.Table || data.TableDescription).TableStatus
  console.log(status)
  if (status != 'ACTIVE') {
    setTimeout(db.describeTable.bind(db, {TableName: 'test'}, checkTable), 100)
  }
}

db.createTable({
  TableName: 'test',
  AttributeDefinitions: [{AttributeName: "id", AttributeType: "S"}],
  KeySchema: [{AttributeName: "id", KeyType: "HASH"}],
  ProvisionedThroughput: {ReadCapacityUnits: "1", WriteCapacityUnits: "1"},
}, checkTable)
```

If I save this to a file and run it I get:
```console
$ node test.js
CREATING
CREATING
CREATING
CREATING
CREATING
ACTIVE
```

**Comment by mhart** [comment]
Perhaps you're binding some state in a closure or memoizing accidentally?
