### ISSUE TITLE
Update LevelDB/UP/DOWN

### ISSUE THREAD

**Issue by chook** [mhart/dynalite#65]
Taking a look at the current state of LevelUP/DOWN it seems a worthy update to DOWN as LevelDB has been updated to 1.19 (after 2 years).

It seems LevelDOWN has upgraded its dependencies to async 2+ so perhaps it's not immediate.

**Comment by mhart** [comment]
Thanks for the nudge! Just updated all deps (including async, may as well bite the bullet) and published as v1.1.0
