### ISSUE TITLE
The getLastEvaluatedKey object returned by the secondary index query is incorrect

### ISSUE THREAD

**Issue by qumingxing** [mhart/dynalite#71]
Hi mhart,

I have a problem,when the query according to the secondary index in the getLastEvaluatedKey only return to the global hashkey,then use this getLastEvaluatedKey object once again to get an error.

In fact AWS DynamoDB will return to global hashkey and the secondary index attribute key-value and so on.

**Comment by mhart** [comment]
@qumingxing I'm sorry, I don't understand what you mean.

Can you show me some code to illustrate?

**Comment by qumingxing** [comment]
Hi mhart,
Thanks for your answer,I have found the cause of the problem.
Sorry I'm mistake.

**Comment by qumingxing** [comment]
Hi mhart,

Thanks for your answer.Here is a code example:
```
BasicAWSCredentials awsCredentials = new BasicAWSCredentials("test", "test");
        Map<String, AttributeValue> lastKeyEvaluated = null;
        AmazonDynamoDBClient dynamoDBClient = new AmazonDynamoDBClient(awsCredentials).withEndpoint("http://192.168.3.187:8081");
        DynamoDBMapper mapper = new DynamoDBMapper(dynamoDBClient);
        Map<String, String> attributeNamesMap = new HashMap<>();
        attributeNamesMap.put("#hashkey", "user_id_group");
        attributeNamesMap.put("#rangekey", "deleted_created_at");
        attributeNamesMap.put("#hashkey", "user_id_group");
        Map<String, AttributeValue> attributeValuesMap = new HashMap<>();
        attributeValuesMap.put(":st_val", new AttributeValue("0_0"));
        attributeValuesMap.put(":ed_val", new AttributeValue("0_3484012576557"));
        attributeValuesMap.put(":hk_val", new AttributeValue("123456_SEARCH"));
        DynamoDBQueryExpression<ChemicalHistory> queryExpression = new DynamoDBQueryExpression<>();
        queryExpression
                .withExpressionAttributeNames(attributeNamesMap)
                .withExpressionAttributeValues(attributeValuesMap)
                .withConsistentRead(false)
                .withScanIndexForward(false)
                .withKeyConditionExpression("#hashkey = :hk_val AND #rangekey between :st_val AND :ed_val")
                .withProjectionExpression("history_id,created_at,history_params,history_type,history_source");
        queryExpression.setIndexName("user_id_group-deleted_created_at");
        queryExpression.setLimit(5);
        do {
            QueryResultPage<ChemicalHistory> results = mapper.queryPage(ChemicalHistory.class, queryExpression.withExclusiveStartKey(lastKeyEvaluated));
            lastKeyEvaluated = results.getLastEvaluatedKey();
        } while (null != lastKeyEvaluated);
```

1. This code works fine in DynamoDB Local.
2. But in dynalite throw exception "com.amazonaws.AmazonServiceException: The provided starting key is invalid" when second for loop execution,and if remove "withProjectionExpression("history_id,created_at,history_params,history_type,history_source")" is ok,I don't  know what the cause is.

**Comment by mhart** [comment]
@qumingxing great – can you also show me the configuration for the table? what does the `user_id_group-deleted_created_at` index look like?

**Comment by qumingxing** [comment]
@mhart 
This is my table structure:

AttributeName|KeyType
------------ | ------------- | 
history_id  |	HASH	

Index Name |  Index Type | Hash Key | Range Key
------------ | ------------- | ------------- | -------------
user_id-deleted_created_at|	          Global|	        user_id|	             deleted_created_at
user_id_type-deleted_created_at|	  Global|	        user_id_type|	     deleted_created_at
user_id_group-deleted_created_at|	  Global|	        user_id_group|	     deleted_created_at

**Comment by mhart** [comment]
@qumingxing great, ok thanks – I'll look into this and see what I can find 👍

**Comment by spatel-cog** [comment]
I believe this can be resolved by modifying db/index.js
The code which filters out results based on attributes set (around lines 853-857) can be moved to after line 861. 
This seems to work for me - just wondered if there were any side affects.
