### ISSUE TITLE
create table promise resolves before table is created.

### ISSUE THREAD

**Issue by chessIthaca** [mhart/dynalite#78]
The following code fails with resource not found:

           dynDb.createTable(
            {
              TableName : DeltaDatabase.CustomerTable,
              KeySchema: [       
                  { AttributeName: "name", KeyType: "HASH"},  //Partition key
              ],
              AttributeDefinitions: [       
                  { AttributeName: "name", AttributeType: "S" },
              ],
              ProvisionedThroughput: {       
                  ReadCapacityUnits: 1, 
                  WriteCapacityUnits: 1
              }
            }).promise().then(value2=> { 
                  return this.dynDb.putItem({
                  TableName: DeltaDatabase.CustomerTable,
                  Item: attr.wrap({
                     name: nameParam,
                     customerId: "123"
                });

If I add a sleep of 1000 ms before the putItem it will succeed.

sleep is implemented as follows:
 delay(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
 }

**Comment by mhart** [comment]
Hi @chessIthaca – this is intended (and what happens in the real DynamoDB). See this issue for more: https://github.com/mhart/dynalite/issues/73
