### ISSUE TITLE
CONTAINS does not support Lists

### ISSUE THREAD

**Issue by ddearing** [mhart/dynalite#80]
According to the AWS documentation (and field testing), the conditional CONTAINS supports Lists., but dynalites implementation does not. 
 
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html

"CONTAINS is supported for lists: When evaluating "a CONTAINS b", "a" can be a list; however, "b" cannot be a set, a map, or a list."

**Comment by mhart** [comment]
Fixed in v2.1.0
