### ISSUE TITLE
Please support TagResource as no-op

### ISSUE THREAD

**Issue by bboreham** [mhart/dynalite#81]
I have some [TagResource](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TagResource.html) calls in my code to help break down our AWS costs, but they break when run locally because they are rejected by dynalite (via localstack):

    UnknownOperationException: An unknown operation was requested.

I don't need dynalite to actually do anything with the tag, just ignore it is fine.

**Comment by andrewkrug** [comment]
It would actually be great if this could support tagging.  I'd love to be able to test table discovery and such against a local instance of dynamodb.
