### ISSUE TITLE
Shouldn't be able to put items with empty lists or empty maps

### ISSUE THREAD

**Issue by erykwarren** [mhart/dynalite#82]
From the [documentation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html): 

> Set type attributes cannot be empty. Requests with empty values will be rejected with a 
> ValidationException exception.

Surprisingly, the AWS console allows you to insert such records using the UI, but that restriction for sure exists in the DynamoDB API.

To reproduce:
```js
dynamo.put({
  TableName: 'yourTable',
  Item: {
    partitionKey: 'value',
    emptyList: [],
    emptyMap: {},
  }
});
```

**Comment by mhart** [comment]
@erykwarren that's for set types, not lists or maps – going to close – but if you can show an error that occurs on production DynamoDB that doesn't occur on dynalite, I'll reopen

**Comment by erykwarren** [comment]
@mhart My bad, sorry.

**Comment by mhart** [comment]
np 👍
