### ISSUE TITLE
Limit in scan operation does not return LastEvaluatedKey correctly

### ISSUE THREAD

**Issue by cdhowie** [mhart/dynalite#86]
For a [scan](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html) operation, the Limit input parameter is (emphasis mine):

> The maximum number of items to **evaluate (not necessarily the number of matching items)**. If DynamoDB processes the number of items up to the limit while processing the results, it stops the operation and returns the matching values up to that point, and a key in `LastEvaluatedKey` to apply in a subsequent operation, so that you can pick up where you left off.

If I have a table in a dynalite database and I issue a scan with a filter condition and a limit less than the number of records in the table, I am not seeing a `LastEvaluatedKey` in the response, which makes it impossible to continue the operation.

**Comment by dkong-d2l** [comment]
I have found this issue myself and have proposed a fix for it [here](https://github.com/mhart/dynalite/pull/89)...

**Comment by mhart** [comment]
Thanks for reporting – this should be fixed in v1.2.1 – please give it a shot and tell me if it works for you 👍
