### ISSUE TITLE
batchGetItem returning error when resource not found

### ISSUE THREAD

**Issue by brkattk** [mhart/dynalite#87]
Correct me if I'm wrong, but batchGetItem should not return a NotFound error when a resource key is not found.

> If a requested item does not exist, it is not returned in the result.

[BatchGetItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html)

**Comment by mhart** [comment]
@brkattk can you please post some code that can reproduce this? Are you sure the table you're querying exists?

**Comment by mhart** [comment]
Going to close this due to lack of activity – feel free to reopen if you have some code that can reproduce this.
