### ISSUE TITLE
Fails to instantiate new dynalite

### ISSUE THREAD

**Issue by cSchubes** [mhart/dynalite#93]
When attempting to create a dynalite server in Typescript like so:
```
import dynalite from 'dynalite'
let dynaliteServer = dynalite({ path: './mydb', createTableMs: 50 })
```
I am getting an error: _Cannot find module 'levelup/lib/errors' from 'shell.js_

I checked the levelup module in my node_modules and indeed, lib only contains three files: batch.js, levelup.js, and promisify.js.

What is going on here?

**Comment by mhart** [comment]
@cSchubes can you give me some details on what versions of node and npm you're using?

**Comment by cSchubes** [comment]
node 6, and using yarn

**Comment by cSchubes** [comment]
When I remove the dynaliteServer line, the error goes away.

**Comment by mhart** [comment]
Hmmm, there might be an incompatibility with `level-sublevel` and `levelup` here – let me look into it

**Comment by mhart** [comment]
I don't get this when I execute the same code in node:
```js
const dynalite = require('dynalite')
let dynaliteServer = dynalite({ path: './mydb', createTableMs: 50 })
```

**Comment by mhart** [comment]
`level-sublevel` will use the version of `level` that's in its own `node_modules` directory (if it exists)

```
$ ls node_modules/level-sublevel/node_modules/levelup/lib
batch.js        codec.js        encodings.js    errors.js       levelup.js      read-stream.js  util.js         write-stream.js
```

Maybe yarn isn't installing it correctly?

**Comment by mhart** [comment]
FWIW, when I do `yarn add dynalite` it installs everything correctly (with yarn 1.7.0)

Can you tell me what the output of `ls node_modules/level-sublevel/node_modules/levelup/lib` is?

**Comment by cSchubes** [comment]
`batch.js  codec.js  encodings.js  errors.js  levelup.js  read-stream.js  util.js  write-stream.js`

That seems to include errors.js, but it isn't looking there for some reason.

**Comment by cSchubes** [comment]
I am using yarn 1.7. I've added it as a devDependency since it is going to be used for testing purposes. Thanks for your quick responses

**Comment by mhart** [comment]
Might be a Typescript issue then – with the way it's importing modules – just try plain Node (and `require`) and see if it works.

**Comment by cSchubes** [comment]
that appears to be it - works with raw JS and node. Thanks for the help!

**Comment by mhart** [comment]
No probs – hope you figure it out!

**Comment by cSchubes** [comment]
Quick update:

Fixed this by changing the `require(levelup/lib/<thing>')` lines into relative imports that look in the node_modules directory. 

I am curious though - why is an internal node_modules directory being created at all? This seems like it would only cause problems like mine. The newest version of level-sublevel (from their repo) has a different package.json that does not require levelup, only libraries like `level-errors`. It may be helpful to update the version of level-sublevel being used in dynalite?

I say all of this without truly understanding how these libraries interact, so take it with a grain of salt. Just wanted to let you know.

**Comment by mhart** [comment]
It's so that each library can declare their own dependencies. If you rely on one version of something and someone else relies on another (major) version, your program wouldn't work if you both tried to require the same package (which is evidently what... typescript? is trying to do).

npm will dedupe shared dependencies as high up the tree as they can go – and sometimes that's only as high as the module requiring it

**Comment by mhart** [comment]
The latest version of level-sublevel (with the changes you describe) was only published 10 hours ago... so yes, I'll look into updating it for dynalite now.

**Comment by cSchubes** [comment]
thanks for explaining that. I'm still new to the world of node, javascript, and typescript so apologies for my ignorance! I'll update this thread if I get it to work using no-hoist or some other technique.

**Comment by mhart** [comment]
Turns out level-sublevel@6.6.4 introduces some major breaking changes. https://github.com/dominictarr/level-sublevel/pull/116#issuecomment-403541860

Will look at moving to subleveldown as suggested there
