### ISSUE TITLE
`((` in ConditionExpression -- parity with prod or oversight?

### ISSUE THREAD

**Issue by dimaqq** [mhart/dynalite#99]
https://github.com/mhart/dynalite/blob/0641c3bf29b1171a67f49d58ca47ad676e145884/db/conditionParser.pegjs#L123

Contains following validation for `ConditionExpression`:

`    if (!errors.parens && text().indexOf('((') === 0) {`

The language for condition expressions includes both `AND` and `OR`, thus, it is possible to construct irreducible expressions with arbitrary number of repeated parentheses:

```
a OR b
(a OR b) AND (c OR d)
((a OR b) AND (c OR d) OR (...) AND (...)) AND ((...) AND (...) OR (...) AND (...))
```

Thus the question is, if this test was for parity with real dynamodb or an oversight / simplified implementation? If this was a limitation of real dynamodb at the time, is it still the case?

I've ran into this when I tried to change the test backend from dynamodb local to dynalite. The error I get and the expression in question are same as described in https://github.com/boto/boto3/issues/1395 (`Attr(attr1).gt(value1) & Attr(attr2).gt(value2) & Attr(attr3).gt(value3)` which boto3 translates to `((a AND b) and C)`).

**Comment by dimaqq** [comment]
I've tested real dynamodb, here's current behaviour:

```
--condition-expression '((:p1 = :p1 AND :p1 = :p1) AND :p1 = :p1)'  # OK
--condition-expression '((:p1 = :p1 AND :p1 = :p1))'  # Redundant parentheses
```

It seems that in this case, dynalite deviates from dynamodb.

**Comment by mhart** [comment]
Yep, I think I just took a shortcut here. Would be happy for a PR to fix this

**Comment by mhart** [comment]
(from memory it was difficult in peg.js to determine redundant parens as they were eliminated – but it was a long time ago)

**Comment by ojii** [comment]
It's late on a Friday night, so I'm not super confident in this, but given the two examples by dimaqq, the following code gives the correct result for both examples:

```js
function has_redundant_parentheses(expr) {
    if (expr.substring(0, 2) !== '((') {
        return false
    }
    var length = expr.length;
    if (expr.substring(length - 2, length) !== '))') {
        return false
    }
    var depth = 1;
    for (var index = 1; index < length; index++) {
        var char = expr[index];
        if (char === '(') {
            depth += 1;
        } else if (char === ')') {
            depth -= 1;
            if (depth === 0) {
                return index === length - 1;
            }
        }
    }
    return false;
}```

The basic idea is to check if it both starts and ends with ((/)) and if the first and last paren match.

**Comment by mhart** [comment]
Awesome. Fri morning here in NYC, so I might have a chance to play with this today – thanks! 👍

**Comment by ojii** [comment]
came up with an updated version, instead of checking if the last and first parens match, check if the second and second-to-last match. If the "inner" parens match, the "outer" must too and are thus redundant. 

```js
function has_redundant_parentheses(expr) {
    if (expr.substring(0, 2) !== '((') {
        return false
    }
    var length = expr.length;
    if (expr.substring(length - 2, length) !== '))') {
        return false
    }
    var depth = 1;
    for (var index = 2; index < length - 1; index++) {
        var char = expr[index];
        if (char === '(') {
            depth += 1;
        } else if (char === ')') {
            depth -= 1;
            if (depth === 0) {
                return index === length - 2;
            }
        }
    }
    return false;
}
```

**Comment by mhart** [comment]
Fixed this in the "correct" way using peg.js: https://github.com/mhart/dynalite/commit/0381387c4359126bda9ead9cb851602f5d944be5#diff-6877405f768ee66ac5f3e9a529bfc10d
